FROM ubuntu:16.04

WORKDIR /root
COPY ebrelayer ebrelayer
COPY ebcli_A ebcli_A
COPY boss4x boss4x
COPY sleep.sh sleep.sh
ENV LD_LIBRARY_PATH /lib/x86_64-linux-gnu/tass
ENV TASS_PCIE_CFG_PATH /etc/tass

CMD ["/root/sleep.sh"]
